import os
import base64
import requests
import io
from fastapi import FastAPI, File, UploadFile, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from PIL import Image

app = FastAPI()

# Enable CORS for frontend communication
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], 
    allow_methods=["*"],
    allow_headers=["*"],
)

# Configuration from environment variables
OPENROUTER_API_KEY = os.environ.get("OPENROUTER_API_KEY", "").strip()
OPENROUTER_URL = "https://openrouter.ai/api/v1/chat/completions"

# Selected Model: Gemini 2.0 Flash (One of the fastest/accurate vision models in 2026)
MODEL_ID = "google/gemini-2.0-flash-001:free"

@app.post("/generate-alt-text")
async def generate_alt_text(file: UploadFile = File(...)):
    if not OPENROUTER_API_KEY:
        raise HTTPException(status_code=500, detail="OPENROUTER_API_KEY is not configured.")

    try:
        # 1. Read the raw file bytes
        file_bytes = await file.read()
        
        # 2. Open with Pillow to handle TIF, PNG, etc.
        try:
            img = Image.open(io.BytesIO(file_bytes))
        except Exception:
            return {"error": "Invalid image file. Please upload a valid JPG, PNG, or TIF."}

        # 3. Pre-processing for Scalability
        # Convert to RGB (required for JPEG saving, especially if TIF/PNG has transparency)
        if img.mode != "RGB":
            img = img.convert("RGB")
        
        # Resize if image is too large (speeds up the API response and prevents timeouts)
        max_size = 1024
        if max(img.width, img.height) > max_size:
            img.thumbnail((max_size, max_size), Image.Resampling.LANCZOS)

        # 4. Save to a byte buffer as a compressed JPEG
        buffer = io.BytesIO()
        img.save(buffer, format="JPEG", quality=85)
        base64_image = base64.b64encode(buffer.getvalue()).decode("utf-8")

        # 5. Prepare OpenRouter Payload
        payload = {
            "model": MODEL_ID,
            "messages": [
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "text", 
                            "text": "Generate a concise, accurate alt-text for this image for accessibility purposes."
                        },
                        {
                            "type": "image_url",
                            "image_url": {
                                "url": f"data:image/jpeg;base64,{base64_image}"
                            }
                        }
                    ]
                }
            ],
            "max_tokens": 100
        }

        headers = {
            "Authorization": f"Bearer {OPENROUTER_API_KEY}",
            "Content-Type": "application/json",
            "HTTP-Referer": "https://alttextapp-production.up.railway.app", # Replace with your URL if needed
            "X-Title": "AltTextApp"
        }

        # 6. Make the API Call
        response = requests.post(OPENROUTER_URL, headers=headers, json=payload, timeout=45)
        
        if response.status_code != 200:
            return {"error": f"API Provider Error {response.status_code}", "details": response.text}

        result = response.json()
        
        if "choices" in result and len(result["choices"]) > 0:
            alt_text = result["choices"][0]["message"]["content"].strip()
            return {"alt_text": alt_text}
        
        return {"error": "No description generated by the model.", "details": result}
        
    except Exception as e:
        print(f"Server error: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)